env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID

language: node_js

os:
  - linux

dist: bionic

node_js:
  - 'lts/*'

install:
  - npm install
  - npm install -g codecov

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - chmod +x ./cc-test-reporter; fi
  - ./cc-test-reporter before-build; fi

script:
  - npm test
  - npm run build
  - codecov

after_script:
  - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
